<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

class Data_desa extends CI_Controller
{
  function __construct()
  {
    parent::__construct();
    $this->load->model('Data_desa_model');

    $this->data['module'] = 'Data Desa';    

    /* cek login */
    if (!$this->ion_auth->logged_in()){
      // apabila belum login maka diarahkan ke halaman login
      redirect('admin/auth/login', 'refresh');
    }
    elseif($this->ion_auth->is_user()){
      // apabila belum login maka diarahkan ke halaman login
      redirect('admin/auth/login', 'refresh');
    }
  }

  public function index()
  {
    $this->data['title'] = "Data Desa";

    $this->data['Data_desa_data'] = $this->Data_desa_model->get_all();
    $this->load->view('back/data_desa/data_desa_list', $this->data);
  }

  public function create() 
  {
    $this->data['title']          = 'Tambah Data Desa Baru';
    $this->data['action']         = site_url('admin/data_desa/create_action');
    $this->data['button_submit']  = 'Submit';
    $this->data['button_reset']   = 'Reset';

    $this->data['id_desa'] = array(
      'name'  => 'id_desa',
      'id'    => 'id_desa',
      'type'  => 'hidden',
    );

    $this->data['nama_desa'] = array(
      'name'  => 'nama_desa',
      'id'    => 'nama_desa',
      'type'  => 'text',
      'class' => 'form-control',
      'value' => $this->form_validation->set_value('nama_desa'),
    );

    $this->load->view('back/data_desa/data_desa_add', $this->data);
  }
  
  public function create_action() 
  {
    $this->load->helper('nama_seo_helper');
    $this->_rules();

    if ($this->form_validation->run() == FALSE) 
    {
      $this->create();
    } 
      else 
      {
        $data = array(
          'nama_desa'  => $this->input->post('nama_desa'),
          'nama_desa_seo'    => nama_seo($this->input->post('nama_desa'))
        );

        // eksekusi query INSERT
        $this->Data_desa_model->insert($data);
        // set pesan data berhasil dibuat
        $this->session->set_flashdata('message', 'Data berhasil dibuat');
        redirect(site_url('admin/data_desa'));
      }  
  }
  
  public function update($id) 
  {
    $row = $this->Data_desa_model->get_by_id($id);
    $this->data['data_desa'] = $this->Data_desa_model->get_by_id($id);

    if ($row) 
    {
      $this->data['title']          = 'Update Data Desa';
      $this->data['action']         = site_url('admin/data_desa/update_action');
      $this->data['button_submit']  = 'Update';
      $this->data['button_reset']   = 'Reset';

      $this->data['id_desa'] = array(
        'name'  => 'id_desa',
        'id'    => 'id_desa',
        'type'  => 'hidden',
      );

      $this->data['nama_desa'] = array(
        'name'  => 'nama_desa',
        'id'    => 'nama_desa',
        'type'  => 'text',
        'class' => 'form-control',
      );

      $this->load->view('back/data_desa/data_desa_edit', $this->data);
    } 
      else 
      {
        $this->session->set_flashdata('message', 'Data tidak ditemukan');
        redirect(site_url('admin/data_desa'));
      }
  }
  
  public function update_action() 
  {
    $this->load->helper('nama_seo_helper');
    $this->_rules();

    if ($this->form_validation->run() == FALSE) 
    {
      $this->update($this->input->post('id_desa'));
    } 
      else 
      {
        $data = array(
          'nama_desa'  => $this->input->post('nama_desa'),
          'nama_desa_seo'    => nama_seo($this->input->post('nama_desa'))
        );

        $this->Data_desa_model->update($this->input->post('id_desa'), $data);
        $this->session->set_flashdata('message', 'Edit Data Berhasil');
        redirect(site_url('admin/data_desa'));
      }
  }
  
  public function delete($id) 
  {
    $row = $this->Data_desa_model->get_by_id($id);
    
    if ($row) 
    {
      $this->Data_desa_model->delete($id);
      $this->session->set_flashdata('message', 'Data berhasil dihapus');
      redirect(site_url('admin/data_desa'));
    } 
      // Jika data tidak ada
      else 
      {
        $this->session->set_flashdata('message', 'Data tidak ditemukan');
        redirect(site_url('admin/data_desa'));
      }
  }

  public function _rules() 
  {
    $this->form_validation->set_rules('nama_desa', 'Nama Desa', 'trim|required');

    // set pesan form validasi error
    $this->form_validation->set_message('required', '{field} wajib diisi');

    $this->form_validation->set_rules('id_desa', 'id_desa', 'trim');
    $this->form_validation->set_error_delimiters('<div class="alert alert-danger alert">', '</div>');
  }

}

/* End of file Data_desa.php */
/* Location: ./application/controllers/Data_desa.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-10-17 02:19:21 */
/* http://harviacode.com */